site_name: Shubham's Digital Garden
site_description: Short nuggets of information, code snippets or articles that I want to keep handy.
copyright: Made with ❤️ by Shubham.
repo_name: ShuLaPy/notes
repo_url: https://github.com/ShuLaPy/notes
edit_uri: blob/main/Obsidian Notes/
docs_dir: Obsidian Notes
site_dir: site
site_author: Shubham Lad

theme:
  name: material
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  shortcuts:
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  language: en
  include_search_page: true
  search_index_only: true
  features:
    - navigation.instant
    - search.share
    - search.highlight
    - search.suggest
  font:
    text: Noto Sans
    code: IMB Plex Mono

plugins:
  - search:
      separator: '[\s\-\.]+'
      prebuild_index: python
      lang:
        - en
  - minify:
      minify_html: true
  - roamlinks
  - mermaid2
  - encryptcontent:
      # use_secret: 'ENCRYPTCONTENT_PASSWORD'
      remember_password: True
      # global_password: 'your_password'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ShuLaPy
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ShuLaPy_
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shubhamlad/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@zeuada
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/shubhintech/

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: true

extra_css:
  - assets/stylesheets/extra.css